/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hollow_knight_silksong.glb
Author: Seifert (https://sketchfab.com/Peter_Seifert)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shaw-hornet-hollow-knight-silksong-670a87a9234c40bc9c2a4f274f6d8cc1
Title: SHAW ! Hornet - Hollow Knight Silksong
*/

import React, { useMemo, useRef, useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { Sparkles } from '@react-three/drei'
import * as THREE from 'three'

export function HollowKnightSilksong(props) {
  const group = useRef()
  // Đường dẫn đúng tới file trong thư mục public
  const { scene, animations } = useGLTF('/models/hollow_knight_silksong.glb')
  // Clone để tránh share skeleton giữa nhiều instance
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)

  // Play animation (nếu có). Nếu không có, model sẽ vẫn là static pose.
  useEffect(() => {
    if (!actions) return
    console.log('Animation clips:', names) // xem tên clip nếu cần
    const first = Object.values(actions)[0]
    if (first) {
      first.reset().fadeIn(0.4).play()
      // Nếu muốn tạo dáng rồi đứng yên, dùng LoopOnce + clamp:
      // first.setLoop(THREE.LoopOnce, 0)
      // first.clampWhenFinished = true
      // first.play()
    }
    return () => first?.fadeOut(0.2)
  }, [actions, names])

  // Bật shadow
  useEffect(() => {
    clone.traverse((obj) => {
      if (obj.isMesh) {
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })
  }, [clone])

  return (
    <group ref={group} {...props} dispose={null}>
      <Sparkles count={2000} speed={2} opacity={1} scale={[30, 25, 30]} size={30} color="#e0f7ff" noise={1}
      />
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="HORNET_RIG_35">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="DRESS001_32" />
                  <group name="HORNET_BODY001_33" />
                  <group name="NEEDLE001_34" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.DRESS} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.HEAD} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.BODY} skeleton={nodes.Object_10.skeleton} />
                  <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.NEEDLE} skeleton={nodes.Object_12.skeleton} />
                </group>
              </group>
              <group name="SILK_LINE_36">
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.SILK_LINE_MATERIAL} />
              </group>
              <group name="SHADOW_37">
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.shadow} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

// Preload để tải sớm khi idle
useGLTF.preload('/models/hollow_knight_silksong.glb')
