/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ARKON-83 (https://sketchfab.com/ARKON-83)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pochita-91023b6e85b4463eacad786496c233a0
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Pochita(props) {
  const { nodes, materials } = useGLTF('/models/pochita.glb')
  const groupRef = useRef()

  // Subtle floating and breathing animation
  useFrame((state) => {
    if (groupRef.current) {
      // Gentle floating motion
      groupRef.current.position.y = Math.sin(state.clock.elapsedTime * 0.8) * 0.08
      // Subtle rotation wobble
      groupRef.current.rotation.z = Math.sin(state.clock.elapsedTime * 0.6) * 0.03
    }
  })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group scale={0.015}>
        <group position={[1137.666, 141.923, 2.315]} rotation={[-Math.PI / 2, 0, 0]} scale={3.326}>
          <mesh
            geometry={nodes.Pochita_Remesh001_Material_0.geometry}
            material={materials.Material}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Pochita_Remesh001_Material003_0.geometry}
            material={materials['Material.003']}
            castShadow
            receiveShadow
          />
          <mesh
            geometry={nodes.Pochita_Remesh001_Material001_0.geometry}
            material={materials['Material.001']}
            castShadow
            receiveShadow
          />
        </group>

        <mesh
          geometry={nodes.Cube016_Material001_0.geometry}
          material={materials['Material.001']}
          position={[1138.672, 262.855, -23.26]}
          rotation={[-2.094, 0, 0]}
          scale={71.985}
          castShadow
          receiveShadow
        />

        <mesh
          geometry={nodes.Cube018_Material002_0.geometry}
          material={materials['Material.002']}
          position={[1137.666, 207.194, 55.27]}
          rotation={[-2.094, 0, 0]}
          scale={[42.09, 100, 100]}
          castShadow
          receiveShadow
        />

        <mesh
          geometry={nodes.NurbsPath004_Material001_0.geometry}
          material={materials['Material.001']}
          position={[1137.666, 77.157, -127.576]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[23.64, 100, 100]}
          castShadow
          receiveShadow
        />

        <mesh
          geometry={nodes.Cube017_Material001_0.geometry}
          material={materials['Material.001']}
          position={[1137.666, 100.141, -118.636]}
          rotation={[-Math.PI / 4, 0, 0]}
          scale={7.774}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/pochita.glb')
